### ISSUE TITLE
FAQS

### ISSUE THREAD

**Issue by VDliveson** [MicrosoftStudentChapter/Makeathon-4.0#13]
![image](https://user-images.githubusercontent.com/72307306/149649895-8aab1776-93af-4bb0-9583-056ffc6cbe9c.png)

**Comment by VishistB** [comment]
I would like to take this up

**Comment by ved-ant** [comment]
i would like to take this

**Comment by Ave-Eren** [comment]
I'd like to take this up

**Comment by destrex271** [comment]
i can take this up

**Comment by BlacBear00** [comment]
I am interested to work on this

**Comment by dikshantgupta2589** [comment]
I am interested to take this

**Comment by mdhvg** [comment]
I'd like to take this up.

**Comment by harishpariyar07** [comment]
I'd like to take this up.

**Comment by harishpariyar07** [comment]
I'd like to take this up.

**Comment by pkkaur13** [comment]
I would like to take this issue
