### ISSUE TITLE
About Us

### ISSUE THREAD

**Issue by VDliveson** [MicrosoftStudentChapter/Makeathon-4.0#14]
![image](https://user-images.githubusercontent.com/72307306/149649939-02ac2f63-3c29-494c-b40c-76fdfa917688.png)

**Comment by IshaniVashishat** [comment]
I want to take this issue.

**Comment by ayushiv2** [comment]
I would like to take this up

**Comment by Once-kaur** [comment]
I want to take up this issue

**Comment by yashxa** [comment]
I would like to take this up

**Comment by achintya406** [comment]
i would like to take up this task

**Comment by pkkaur13** [comment]
I would like to take this issue

**Comment by VDliveson** [comment]
closes #14
