### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by aarushi353** [MicrosoftStudentChapter/Makeathon-4.0#15]

**Comment by nimishmedatwal** [comment]
i can take this up

**Comment by destrex271** [comment]
i can take this

**Comment by utkarsh-1905** [comment]
I want this

**Comment by Ave-Eren** [comment]
I wish to take this up

**Comment by nandinitiet** [comment]
i would like to take this up

**Comment by BawejaMoksh** [comment]
willing to take one up not assigned any

**Comment by SiyaSindhani** [comment]
I'd like to take this up

**Comment by harishpariyar07** [comment]
I'd like to take this up.

**Comment by aarushi353** [comment]
![Screenshot 2022-01-16 133323](https://user-images.githubusercontent.com/72608824/149652773-8df802d5-fa80-4973-8f13-8f4b07e2e915.png)

**Comment by aarushi353** [comment]
![Screenshot 2022-01-16 133240](https://user-images.githubusercontent.com/72608824/149652779-3352ece2-7a32-4c82-9423-c55b1f6ac8e4.png)

**Comment by aarushi353** [comment]
![Screenshot 2022-01-16 133305](https://user-images.githubusercontent.com/72608824/149652789-33a38bf1-1f83-4b7e-b175-9601f5010012.png)

**Comment by pkkaur13** [comment]
I would like to take this issue
