### ISSUE TITLE
Sponsors Page

### ISSUE THREAD

**Issue by aarushi353** [MicrosoftStudentChapter/Makeathon-4.0#16]
![Screenshot 2022-01-16 123656](https://user-images.githubusercontent.com/72608824/149650750-72a96667-6b25-450b-af8b-d88d3fb85d0c.png)
![Screenshot 2022-01-16 123709](https://user-images.githubusercontent.com/72608824/149650762-6dd0fc22-9de5-43fa-842a-5b6cc27847c9.png)

**Comment by ananyabansal16** [comment]
I would like to take this issue.

**Comment by adityapathakk** [comment]
i'd like to work on this issue!

**Comment by mohak2908** [comment]
I would like to take this issue

**Comment by Akshitaj25** [comment]
i would like to take this

**Comment by pkkaur13** [comment]
I would like to take this issue
