### ISSUE TITLE
Judges Page

### ISSUE THREAD

**Issue by aarushi353** [MicrosoftStudentChapter/Makeathon-4.0#18]
![image](https://user-images.githubusercontent.com/72608824/149650704-8c534954-9d23-44a5-a5d6-fab87531c381.png)

**Comment by Ave-Eren** [comment]
I would like to take this up too

**Comment by VishistB** [comment]
I'd like to take this up

**Comment by ghost** [comment]
I would like to take this up.

**Comment by sanchirang** [comment]
I want to work on this

**Comment by achintya406** [comment]
i want to work on this

**Comment by harishpariyar07** [comment]
i'd like to take this up.

**Comment by pkkaur13** [comment]
I would like to take this issue
