### ISSUE TITLE
Timeline Page 

### ISSUE THREAD

**Issue by VDliveson** [MicrosoftStudentChapter/Makeathon-4.0#21]
![image](https://user-images.githubusercontent.com/72307306/149718659-6ccdbcc5-2584-4308-80b1-90e0193249c1.png)

Will try to get mobile view design asap

**Comment by pkkaur13** [comment]
I would like to take this issue

**Comment by jimbo-exe** [comment]
I would like to work on this issue

**Comment by Yashvi30** [comment]
I would like to take up this issue.

**Comment by Tithi-S** [comment]
i would like to take up this issue

**Comment by pkkaur13** [comment]
I would like to work on this issue

**Comment by prakhar-7129** [comment]
I would like to work on this issue

**Comment by harishpariyar07** [comment]
I would like to take up this issue.

**Comment by gandhi25samar** [comment]
I would like to take this up
