### ISSUE TITLE
Contact us page bugs

### ISSUE THREAD

**Issue by RGTechPro** [MicrosoftStudentChapter/Makeathon-4.0#39]
![8c3b1548-3e89-4a5e-8e30-6f66a31f74ce](https://user-images.githubusercontent.com/73791635/150156531-64f0a5db-0ab4-4fa0-b2cf-b3ca8f456524.jpg)
1)Padding and margin needed in footer
2)Text overlap in header
3)Too much space at the bottom

**Comment by arorasukhmani** [comment]
I will like to work on this issue

**Comment by gandhi25samar** [comment]
I will like to work on this issue

**Comment by rishabhgl** [comment]
I would like to work on this issue
