### ISSUE TITLE
About-Us responsive bug 

### ISSUE THREAD

**Issue by VDliveson** [MicrosoftStudentChapter/Makeathon-4.0#40]
## From 719-300px 
![image](https://user-images.githubusercontent.com/72307306/150158146-9d140a62-68a5-478d-839b-f22686b32bb0.png)

**Comment by rishabhgl** [comment]
I would like to work on this

**Comment by Ave-Eren** [comment]
I can take this up

**Comment by utkarsh-1905** [comment]
I can take this up

**Comment by ChetandeepSingh** [comment]
I can take this up

**Comment by ChetandeepSingh** [comment]
i want to take this up
