### ISSUE TITLE
Updating and fixing backgrounds

### ISSUE THREAD

**Issue by aarushi353** [MicrosoftStudentChapter/Makeathon-4.0#61]
For the following sections ->
Speakers
Judges Page
Prizes and tracks (fix it)

**Comment by Akshitaj25** [comment]
i can do this

**Comment by Samriddh-Bhatla** [comment]
I would like to work on this

**Comment by adityapathakk** [comment]
I can work on this!

**Comment by ananyabansal16** [comment]
i can work on this issue
