### ISSUE TITLE
Prizes Page

### ISSUE THREAD

**Issue by aarushi353** [MicrosoftStudentChapter/Makeathon-4.0#8]
![image](https://user-images.githubusercontent.com/72307306/149649923-cd9d67b4-15ce-4740-82d1-c80ad5ef7141.png)

**Comment by PikaPool2402** [comment]
i want to take this up!

**Comment by namanarora3** [comment]
i want to take this up!

**Comment by Samriddh-Bhatla** [comment]
I can do this

**Comment by Aitchessbee** [comment]
I can take this up

**Comment by Ikshan-Tango** [comment]
I will work on it

**Comment by Avirat201189221** [comment]
i can take this up

**Comment by Ishan19agarwal** [comment]
i can take this up

**Comment by ghost** [comment]
I would like to take this issue

**Comment by vteam27** [comment]
i can take this up !

**Comment by Vansh-Batra10** [comment]
I want to take this issue

**Comment by BhavyaBhalla27** [comment]
I want to take this issue

**Comment by Yashvi30** [comment]
I want to work on this.

**Comment by destrex271** [comment]
I will work on it !!

**Comment by utkarsh-1905** [comment]
**I WILL WORK ON IT**

**Comment by IshaniVashishat** [comment]
I want to work on this.

**Comment by Ave-Eren** [comment]
I will work on this too

**Comment by JhndaCoder** [comment]
i want to work

**Comment by Tithi-S** [comment]
i want to work

**Comment by sanchirang** [comment]
I want to work on this

**Comment by manassinghal95** [comment]
I want to try

**Comment by ved-ant** [comment]
i want to take it

**Comment by Ishan-Panwar** [comment]
i want to work as well

**Comment by yashxa** [comment]
i would like to take this issue

**Comment by Ishan-Panwar** [comment]
I want to work on this

**Comment by pkkaur13** [comment]
I would like to take this issue
